### ISSUE TITLE
用了半天总算调试好了，目前用起来还不错，作者可能比较懒，没有写清楚用法，例子中还有一点错误，我完善一些用法吧。

### ISSUE THREAD

**Issue by lnjzwy1976** [theanarkh/nodejs-threadpool#2]
安装模块：
npm install -S nodejs-threadpool

使用：
  模块中主要对象threadPool一共开放了8个接口，前4个分别是：
    ThreadPool 基础类，可以自由配置线程数；
    CPUThreadPool类 以CPU核心数为线程数；
    SingleThreadPool类 单线程；
    FixedThreadPool类 没研究；
    后面4个default开头的是前4个类的默认配置对象。

  基本上常用的就是ThreadPool基础类和CPUThreadPool类。
  除了threadPool对象外还有2个config和constants，分别是常量和类型，不用关心。

例子：
------创建线程的js代码-----------------------------------------------------------
    const threadPool=require('nodejs-threadpool').threadPool;   //引入模块，作者的例子中require('nodejs-thread-pool')是错的
    //自定义配置
    const options={
      coreThreads:10, // 核心线程数
      expansion:false, //是否支持动态线程，如果false最大线程数为coreThreads,最大线程数默认50，在config.js中MAX_THREADS修改
      discardPolicy:5,  //超过任务队列长度时的处理策略,constants.js中DISCARD_POLICY结构，默认不丢弃
      preCreate:false, //是否预创建子线程
      maxIdleTime:10 * 60 * 1000,  //线程最大空闲时间，达到后自动退出,毫秒。
      maxWork:Infinity,   //最大任务数
      // timeout:   //任务超时时间
    }
    //创建一个多线程对象
    const wokerObj=new threadPool.ThreadPool(options);  
    //如果是线程执行js文件需要path模块
    const path = require('path');  
    //submit方法提交任务到线程池，因为是异步操作所以需要用await等待返回一个线程对象，为了定义后面的on事件，
    //第一个参数可以是js文件或者是js代码，如果是js文件必须是绝对路径，如果是js代码必须是一个函数，
    //第二个参数是传递给线程的参数，因为只能传一个值，所以最方便的就是把所有参数装进一个对象
    const worker =await wokerObj.submit(path.resolve(__dirname, './src/makeDisp.js'),{op1:123,op2:'ab'}); 
      worker.on('done', function() {
        console.log(...arguments);  //打印了被执行的任务rerurn回来的值。
      });
      worker.on('error', function() {
        console.log(...arguments);  //如果出错，打印错误信息
      });
    ...其他代码
-----创建线程js结束----------------------------------------------------------------
-----makeDisp.js内容---------------------------------------------------------------
    module.exports = function (op) {
        const {op1,op2}=op;  //解构参数
        ...其他代码
        return op1+op2;   //这个会回传到创建线程
        }
-----makeDisp.js结束----------------------------------------------------------------

**Comment by theanarkh** [comment]
> 安装模块：
> npm install -S nodejs-threadpool
> 
> 使用：
> 模块中主要对象threadPool一共开放了8个接口，前4个分别是：
> ThreadPool 基础类，可以自由配置线程数；
> CPUThreadPool类 以CPU核心数为线程数；
> SingleThreadPool类 单线程；
> FixedThreadPool类 没研究；
> 后面4个default开头的是前4个类的默认配置对象。
> 
> 基本上常用的就是ThreadPool基础类和CPUThreadPool类。
> 除了threadPool对象外还有2个config和constants，分别是常量和类型，不用关心。
> 
> 例子：
> ------创建线程的js代码-----------------------------------------------------------
> const threadPool=require('nodejs-threadpool').threadPool; //引入模块，作者的例子中require('nodejs-thread-pool')是错的
> //自定义配置
> const options={
> coreThreads:10, // 核心线程数
> expansion:false, //是否支持动态线程，如果false最大线程数为coreThreads,最大线程数默认50，在config.js中MAX_THREADS修改
> discardPolicy:5, //超过任务队列长度时的处理策略,constants.js中DISCARD_POLICY结构，默认不丢弃
> preCreate:false, //是否预创建子线程
> maxIdleTime:10 * 60 * 1000, //线程最大空闲时间，达到后自动退出,毫秒。
> maxWork:Infinity, //最大任务数
> // timeout: //任务超时时间
> }
> //创建一个多线程对象
> const wokerObj=new threadPool.ThreadPool(options);
> //如果是线程执行js文件需要path模块
> const path = require('path');
> //submit方法提交任务到线程池，因为是异步操作所以需要用await等待返回一个线程对象，为了定义后面的on事件，
> //第一个参数可以是js文件或者是js代码，如果是js文件必须是绝对路径，如果是js代码必须是一个函数，
> //第二个参数是传递给线程的参数，因为只能传一个值，所以最方便的就是把所有参数装进一个对象
> const worker =await wokerObj.submit(path.resolve(__dirname, './src/makeDisp.js'),{op1:123,op2:'ab'});
> worker.on('done', function() {
> console.log(...arguments); //打印了被执行的任务rerurn回来的值。
> });
> worker.on('error', function() {
> console.log(...arguments); //如果出错，打印错误信息
> });
> ...其他代码
> -----创建线程js结束----------------------------------------------------------------
> -----makeDisp.js内容---------------------------------------------------------------
> module.exports = function (op) {
> const {op1,op2}=op; //解构参数
> ...其他代码
> return op1+op2; //这个会回传到创建线程
> }
> -----makeDisp.js结束----------------------------------------------------------------

感谢反馈，库的名称和用法改过了，没有更新文档，有问题欢迎交流！
