### ISSUE TITLE
maxThreads参数无效

### ISSUE THREAD

**Issue by freeflowthought** [theanarkh/nodejs-threadpool#3]
src/threadPool.js文件，在ThreadPool的构造函数中初始化参数 这个逻辑根本没用到options中的maxThreads
// 线程池最大线程数，如果不支持动态扩容则最大线程数等于核心线程数
this.maxThreads = options.expansion !== false ? Math.max(this.coreThreads, config.MAX_THREADS) : this.coreThreads;

**Comment by theanarkh** [comment]
> src/threadPool.js文件，在ThreadPool的构造函数中初始化参数 这个逻辑根本没用到options中的maxThreads
> // 线程池最大线程数，如果不支持动态扩容则最大线程数等于核心线程数
> this.maxThreads = options.expansion !== false ? Math.max(this.coreThreads, config.MAX_THREADS) : this.coreThreads;

211行不是使用了吗
