### ISSUE TITLE
worker退出有bug

### ISSUE THREAD

**Issue by freeflowthought** [theanarkh/nodejs-threadpool#4]
`  // 创建线程
    newThread() {
        const worker = new Worker(workerPath);
        const thread = new Thread({worker});
        this.workerQueue.push(thread);
        const threadId = worker.threadId;
        worker.on('exit', () => {
            // 找到该线程对应的数据结构，然后删除该线程的数据结构
            const position = this.workerQueue.findIndex(({worker}) => {
                return worker.threadId === threadId;
            });
            const exitedThread = this.workerQueue.splice(position, 1);
            // 退出时状态是BUSY说明还在处理任务（非正常退出）
            this.totalWork -= exitedThread.state === THREAD_STATE.BUSY ? 1 : 0;
        });
        // 和子线程通信
        worker.on('message', (result) => {
            const {
                work,
                event,
            } = result;
            const { data, error, workId } = work;
            // 通过workId拿到对应的userWork
            const userWork = this.workPool[workId];
            // 不存在说明任务被取消了
            if (!userWork) {
                return;
            }
            // 修改线程池数据结构
            this.endWork(userWork);

            // 修改线程数据结构
            thread.setLastWorkTime(Date.now());
            
            // 还有任务则通知子线程处理，否则修改子线程状态为空闲
            if (this.queue.length) {
                // 从任务队列拿到一个任务交给子线程
                this.submitWorkToThread(thread, this.queue.shift());
            } else {
                thread.setState(THREAD_STATE.IDLE);
            }
           
            switch(event) {
                case 'done':
                    // 通知用户，任务完成
                    userWork.emit('done', data);
                    break;
                case 'error':
                    // 通知用户，任务出错
                    if (EventEmitter.listenerCount(userWork, 'error')) {
                        userWork.emit('error', error);
                    }
                    break;
                default: break;
            }
        });
        worker.on('error', (...rest) => {
            console.error(...rest);
        });
        return thread;
    }`

在这个方法中  worker.on('exit', ()=>{ 
//在这里 worker.theadId已经变成-1了 ，但是在外边 给这个赋值为 const threadId = worker.threadId; 还是原来的值，这两个值两个是不可能相等的，因此不会从workerQueue中移出，下次调用，postmessage就会无效
},

**Comment by theanarkh** [comment]
> ` // 创建线程
> newThread() {
> const worker = new Worker(workerPath);
> const thread = new Thread({worker});
> this.workerQueue.push(thread);
> const threadId = worker.threadId;
> worker.on('exit', () => {
> // 找到该线程对应的数据结构，然后删除该线程的数据结构
> const position = this.workerQueue.findIndex(({worker}) => {
> return worker.threadId === threadId;
> });
> const exitedThread = this.workerQueue.splice(position, 1);
> // 退出时状态是BUSY说明还在处理任务（非正常退出）
> this.totalWork -= exitedThread.state === THREAD_STATE.BUSY ? 1 : 0;
> });
> // 和子线程通信
> worker.on('message', (result) => {
> const {
> work,
> event,
> } = result;
> const { data, error, workId } = work;
> // 通过workId拿到对应的userWork
> const userWork = this.workPool[workId];
> // 不存在说明任务被取消了
> if (!userWork) {
> return;
> }
> // 修改线程池数据结构
> this.endWork(userWork);
> 
> ```
>         // 修改线程数据结构
>         thread.setLastWorkTime(Date.now());
>         
>         // 还有任务则通知子线程处理，否则修改子线程状态为空闲
>         if (this.queue.length) {
>             // 从任务队列拿到一个任务交给子线程
>             this.submitWorkToThread(thread, this.queue.shift());
>         } else {
>             thread.setState(THREAD_STATE.IDLE);
>         }
>        
>         switch(event) {
>             case 'done':
>                 // 通知用户，任务完成
>                 userWork.emit('done', data);
>                 break;
>             case 'error':
>                 // 通知用户，任务出错
>                 if (EventEmitter.listenerCount(userWork, 'error')) {
>                     userWork.emit('error', error);
>                 }
>                 break;
>             default: break;
>         }
>     });
>     worker.on('error', (...rest) => {
>         console.error(...rest);
>     });
>     return thread;
> }`
> ```
> 
> 在这个方法中 worker.on('exit', ()=>{
> //在这里 worker.theadId已经变成-1了 ，但是在外边 给这个赋值为 const threadId = worker.threadId; 还是原来的值，这两个值两个是不可能相等的，因此不会从workerQueue中移出，下次调用，postmessage就会无效
> },

感谢反馈，已修复，有空可以看一下。
