### ISSUE TITLE
引入脚本希望能加入对es6方式的支持

### ISSUE THREAD

**Issue by FVampire** [theanarkh/nodejs-threadpool#5]
worker.js 中的代码
if (!isFunction(aFunction)) {
            throw new Error('work type error: js file or string');
        }
        work.data = await aFunction(options);
        parentPort.postMessage({event: 'done', work});

我目前改成这样在用的
if (isFunction(aFunction)) {
            work.data = await aFunction(options);
            parentPort.postMessage({ event: 'done', work });
            return;
        }
        if (isFunction(aFunction.default)) {
            work.data = await aFunction.default(options);
            parentPort.postMessage({ event: 'done', work });
            return;
        }
        throw new Error('work type error: js file or string');

**Comment by theanarkh** [comment]
好的。

**Comment by theanarkh** [comment]
> worker.js 中的代码
> if (!isFunction(aFunction)) {
> throw new Error('work type error: js file or string');
> }
> work.data = await aFunction(options);
> parentPort.postMessage({event: 'done', work});
> 
> 我目前改成这样在用的
> if (isFunction(aFunction)) {
> work.data = await aFunction(options);
> parentPort.postMessage({ event: 'done', work });
> return;
> }
> if (isFunction(aFunction.default)) {
> work.data = await aFunction.default(options);
> parentPort.postMessage({ event: 'done', work });
> return;
> }
> throw new Error('work type error: js file or string');

好的。

**Comment by theanarkh** [comment]
> > worker.js 中的代码
> > if (!isFunction(aFunction)) {
> > throw new Error('work type error: js file or string');
> > }
> > work.data = await aFunction(options);
> > parentPort.postMessage({event: 'done', work});
> > 我目前改成这样在用的
> > if (isFunction(aFunction)) {
> > work.data = await aFunction(options);
> > parentPort.postMessage({ event: 'done', work });
> > return;
> > }
> > if (isFunction(aFunction.default)) {
> > work.data = await aFunction.default(options);
> > parentPort.postMessage({ event: 'done', work });
> > return;
> > }
> > throw new Error('work type error: js file or string');
> 
> 好的。

已支持，可以试一下，1.0.0-beta-0.0.1版本

**Comment by FVampire** [comment]
你好，很高兴你的回复，但是我想要的是对es6语法的支持，不是对mjs的支持，因为我用的是ts，exports和import

**Comment by theanarkh** [comment]
> 你好，很高兴你的回复，但是我想要的是对es6语法的支持，不是对mjs的支持，因为我用的是ts，exports和import

不是很理解你的需求，可以贴个demo代码，ts也是得转成js才能执行。

**Comment by FVampire** [comment]
export default function foo() {}
ts会编译成 exports.default = foo;
而不是module.exports = foo;

所以你这边worker.js
aFunction = require(filename)
时
aFunction是一个obj 
typeof aFunction.default = 'function'

**Comment by theanarkh** [comment]
> export default function foo() {}
> ts会编译成 exports.default = foo;
> 而不是module.exports = foo;
> 
> 所以你这边worker.js
> aFunction = require(filename)
> 时
> aFunction是一个obj
> typeof aFunction.default = 'function'

试试1.0.0-beta-0.0.2版本

**Comment by FVampire** [comment]
非常感谢，可以了
