### ISSUE TITLE
这个库支持 子线程之间的 信息传递嘛

### ISSUE THREAD

**Issue by SpencerChou** [theanarkh/nodejs-threadpool#9]
这个库支持子线程之间的信息传递嘛，那个什么message channel的内容

**Comment by theanarkh** [comment]
你可以说一下你的场景

**Comment by SpencerChou** [comment]
我可能想的就是类似mpi的那种，需要线程之间同步数据啥的，不过感觉nodejs也不是用来干这个的

不过我更好奇的是，子线程计算完成之后的结果，这个库是能返回给主线程的嘛，我看例子好像都只是console.log

**Comment by theanarkh** [comment]
会传回到调用方。可以参考 https://github.com/theanarkh/nodejs-threadpool/blob/main/test/testEvent/index.js 的 done 事件

**Comment by SpencerChou** [comment]
怎么在本地使用这个包呀

**Comment by theanarkh** [comment]
直接用就可以了

**Comment by SpencerChou** [comment]
直接把包解压到自己的文件夹之下嘛？我放在 npm -i 的局部那个 node_module里面，require的时候报错

**Comment by theanarkh** [comment]
npm i nodejs-threadpool 安装使用

**Comment by SpencerChou** [comment]
不知道大佬何时有空啊，我有点搞不懂vm这么模块，网上也找不到啥讲解，不知道understand nodejs有没有时间可以解析下这个

**Comment by theanarkh** [comment]
vm 模块就是相当于一个 JS 引擎，传入代码执行。主要是调了 V8 的一些 API。

**Comment by SpencerChou** [comment]
大佬，如果我在外边自己定义好了一个函数，或者 从外边require进来一个函数，想submit进线程池怎么办呢，我看到aFunction好像只能是js，mjs，str，然后只能这样提交，但是不能直接提交一个function obj，然后参数传进去
![image](https://user-images.githubusercontent.com/34341763/197408995-fe4f3723-0a02-4920-991b-4333e8f9e46a.png)

**Comment by theanarkh** [comment]
函数不能在线程间传递，你可以说一下你的应用场景

**Comment by SpencerChou** [comment]
就是比如说是类似actor model的场景，别的actor给你发了message，你有新的计算需求，需要利用线程池进行计算，这个时候，actor的模型代码是已经写好了的了，什么信息使用什么函数计算，早已经require进来了，就等着将这个计算任务 扔进线程池，跟Java那种比较像吧，Java那种话说能通过参数直接run一个函数进去等待结果嘛

**Comment by theanarkh** [comment]
这个和c语言传函数指针不一样，js里没办法这样传，你只能传一个文件或者字符串，和一些上下文参数给子线程，然后它会解析字符串为js代码，并且传入你设置的参数，执行代码。

**Comment by SpencerChou** [comment]
> 会传回到调用方。可以参考 https://github.com/theanarkh/nodejs-threadpool/blob/main/test/testEvent/index.js 的 done 事件

那我比较好奇地是，我之前问的，能够通过work.(‘done’）事件，讲计算结果传回来，如果计算结果是一个object，那这玩意儿怎么传回来的，function不也是一个obj嘛。。还是说，其实没法将结果传回来啊？比如我求了一个加法，想通过done事件接受 a+b的值

**Comment by theanarkh** [comment]
对象可以，函数不行。底层用了html那个clone算法，现在的实现不知道有没有办法支持，这个库也好久前的了。

**Comment by theanarkh** [comment]
也可以到npm找一下其他库了解下。

**Comment by SpencerChou** [comment]
![image](https://user-images.githubusercontent.com/34341763/198026467-165a8e05-a29c-4198-a647-7a0d70b321bd.png)
这是什么情况ya呀

**Comment by SpencerChou** [comment]
还有就是这个 threadpool是 handle吗？为什么用了，程序一直不结束呢

**Comment by theanarkh** [comment]
发一下代码看看，threadpool 里面有线程，所以不会退出，目前还没有支持退出，回头加一下

**Comment by SpencerChou** [comment]
好像是因为 我没有await，所以不能.on，话说这是为什么，js的promise我还不太熟

**Comment by theanarkh** [comment]
不await的话你拿到的是一个 promise，就没有 on 方法，await 你拿到的是另一个对象，它有 on 方法。

**Comment by SpencerChou** [comment]
大佬，你觉得，有了线程池，nodejs的cluster还有使用的必要吗？我想在网上找有关此的论述，但是找不到。。感觉cluster 就没必要了，cluster是在 nodejs的 worker thread 出来之前发明的对吧

**Comment by theanarkh** [comment]
cluster 解决的是多个进程监听同一个端口的问题，如果你是说利用多核处理一下 CPU 密集型的任务，那使用多线程是可以的，用 child_process 就显得比较重。从操作系统系统角度来说，多线程相比多进程来说，问题是一个线程 crash 了会导致整个进程 crash，进程则不会，但是 Node.js 里，如果你在线程里处理一些 JS 代码的话倒是可以的，一般也不会有什么 crash 的问题。

**Comment by SpencerChou** [comment]
我现在有这么一个想法，就是 我一个数组中有很多任务，我想按照顺序让这些任务 用线程池执行，虽然submit本身是异步的，但是for循环感觉会阻塞主线程循环，我这儿 测试用for 循环中await，如果是主线程的settimeout那种异步定时的，好像能够按照顺序执行，但是 在线程池这儿实验的时候，发现好像做不到，有什么办法嘛

**Comment by SpencerChou** [comment]
![image](https://user-images.githubusercontent.com/34341763/198053496-38363d76-531f-4c7c-bf64-82c388491e93.png)
代码是这样的，我想通过flag变量控制函数的执行时间来着

**Comment by theanarkh** [comment]
```
const promiseQueue = [1,2,3].map(async () => {
    const worker = await threadpool.submit(...);
    return worker;
})
```

**Comment by SpencerChou** [comment]
![image](https://user-images.githubusercontent.com/34341763/198064053-3ebbab74-9b8c-424c-baa9-965f6a031adc.png)

**Comment by SpencerChou** [comment]
![image](https://user-images.githubusercontent.com/34341763/198064164-fbc78a97-d3ce-48a2-afdb-bad670f55204.png)
这个顺序还是bu'd不定的

**Comment by SpencerChou** [comment]
是线程池无法做到么? 如果是 settimeout这种的反正能做到，整体执行的时间都会变长，因为是顺序执行了

**Comment by theanarkh** [comment]
需要按顺序执行，那一个个提交到线程池就好了，为啥一起提交，提交给线程池，是多个线程同时在跑的，谁先执行完不确定。

**Comment by SpencerChou** [comment]
但是一个个提交会阻塞主线程循环吗？set timeout，随机时间，用await明明可以就是说，时间短的同样是后输出，因为第一个settimeout  定时器到时间了，才会set第二个，我觉得线程池不应该也能这样嘛，因为 我现在是想做一个actor系统，一个actor如果是有信息接受，计算工作交给线程池来做，但是如果同时扔进去，结果就完全不确定了，所以我想一个一个执行，并通过async/await来达到 就是不用阻塞主线程循环的这样一个功能   ，因为一个线程有好多个actor嘛，好多个actor可能同时都有 message接受，然后用线程池来做计算，如果一个actor接收到消息很多消息，mailbox里面有好多消息，我要都给他执行了，不就得这样吗？

**Comment by SpencerChou** [comment]
我其实本意 是想写一个for 循环，但是for循环会阻塞主循环，但是我找不到如何在不写for循环的情况下，能够这样异步的、事件驱动的去顺序执行 mailbox中的每一个message

**Comment by theanarkh** [comment]
你先确定你的任务是不是需要顺序执行，如果是的话，你可以用一个队列存起来，然后逐个给线程池处理就好了。
```
const { defaultThreadPool } = require('nodejs-threadpool').threadPool;
const queue = [];
let processing = false;
async function submit(task) {
    processing = true;
    const work = await defaultThreadPool.submit("function({a, b}) { return a + b; }", task);
    const done = (result) => {
        console.log(result);
        if (queue.length) {
            submit(queue.shift());
        } else {
            processing = false;
        }
    };
    work.on('error', done);
    work.on('done', done);
}
function enqueue(task) {
    if (processing) {
        queue.push(task);
    } else {
        submit(task);
    }
}
enqueue({a: 1, b: 1});
enqueue({a: 2, b: 2})
enqueue({a: 3, b: 3})
```

**Comment by SpencerChou** [comment]
就会有点类似协程，我这个交给线程池的 任务没做完，我把主线程的执行权 交给别人，等这个线程执行完了，我再找时间拥有主线程的执行权，然后将下一个计算任务扔进线程池

**Comment by theanarkh** [comment]
await 就是这样的，await 不代表阻塞主线程，只是函数里 await 后面的代码不能继续执行。
```
async function a() {}
async function test() {
    await a();
    console.log(1);
}
test();
console.log(2);
```

**Comment by SpencerChou** [comment]
是，我的理解是这样，所以我一直就觉得，await了之后，函数中for循环之后的部分应该不会执行了，等这个await执行完了，才会进下一个循环，然后，才会扔下一个任务进线程池，但是好像跑起来不是这样的。我感觉很奇怪，不过大佬上面写的那个也还挺好的

**Comment by theanarkh** [comment]
你那个例子不一样的，你在函数里 await，所以 someFunctions 里面的代码就是串行执行的了，但是你在 someFunctions 后面加代码就可以了执行了，可以先了解下 async await。

**Comment by SpencerChou** [comment]
![image](https://user-images.githubusercontent.com/34341763/198100936-4ddb8ea4-bb33-428b-a7f8-16be6b063a4d.png)
我改了下，想把z值传到外边，但是发现enqueue那儿，如果是push的queue那段，好像enqueue就没办法把值传出来了？

**Comment by SpencerChou** [comment]
不过这个enqueue好像没法把值传到外面来了？，那如果要根据 返回值，最后修改某个状态，感觉是不是 比较难弄

**Comment by theanarkh** [comment]
```
const { defaultThreadPool } = require('nodejs-threadpool').threadPool;
const queue = [];
let processing = false;
async function submit(task) {
    processing = true;
    const work = await defaultThreadPool.submit(task.context.file || "function({a, b}) { return a + b; }", task.context.params);
    if (~~task.context.timeout) {
        work.setTimeout(~~task.context.timeout);
        work.on('timeout', () => {
            task.reject(new Error('timeout'));
        });
    }
    const done = (err, result) => {
        err ? task.reject(err) : task.resolve(result);
        if (queue.length) {
            submit(queue.shift());
        } else {
            processing = false;
        }
    };
    work.on('error', (error) => {
        done(new Error(error));
    });
    work.on('done', (result) => {
        done(null, result)
    });
}
function enqueue(context) {
    return new Promise((resolve, reject) => {
        const task = {
            context,
            resolve,
            reject
        };
        if (processing) {
            queue.push(task);
        } else {
            submit(task);
        }
    })
}
Promise.all([
    enqueue({ params: {a: 1, b: 1}, timeout: 1000 }),
    enqueue({ params: {a: 2, b: 2}, timeout: 1000 }),
    enqueue({ params: {a: 3, b: 3}, timeout: 1000 }),
]).then(console.log);
```

**Comment by SpencerChou** [comment]
大佬确实神，我对js的理解完全没到这种程度，，太强了，至于之前为什么await的那种方案不行，我想到原因了，因为 threadpool submit的promise  resolve的是userwork，所以userwork实际上已经有结果了，所以await就进行了下一个循环，然后线程是同时并行执行的，并没顺序化。

不过我刚刚使用您的代码的时候，结果正常
![image](https://user-images.githubusercontent.com/34341763/198285623-1b944d95-b53e-4e5a-83d3-4b4ad5e9ebec.png)

但是我这样shi'yo使用的时候
![image](https://user-images.githubusercontent.com/34341763/198285776-ecc428f5-03b0-4dc6-b453-45faf9f6691a.png)

**Comment by theanarkh** [comment]
第一个 Promise.all需要加 await。

**Comment by SpencerChou** [comment]
我试过了，加了也是这样子的。。感觉好像在for 循环中就不太行。。
很神奇，我把 for i of j，改成了普通for 循环，结果没有promise了。。
![image](https://user-images.githubusercontent.com/34341763/198328241-333480bf-82b3-4bda-9504-de21899af884.png)

**Comment by SpencerChou** [comment]
我的问题，是[x]的问题，不应该有这个[]

**Comment by SpencerChou** [comment]
我做了这么一个测试，当我尝试用settimeout来测试这个 线程池的返回值是不是 异步非阻塞的时候，settimeout的输出，是很理想的插在了线程池的输出的中间的，证明了 异步使用线程池执行任务，并未阻塞主线程的执行，但是当我连续调用两次dispatcher tst的时候，我把线程池计算的时间拉的很长，所以说第一个测试的时候，第一个任务应该要很久才能做完，这样第二个任务才会插入线程池，此时第二个异步的 test的第一个任务，应当是插进了线程池并执行了任务。在我的理解中应当会出现交替打印的情况，可是不仅没出现这个情况，反而 单一的线程的打印的顺序反而还不是顺序了，还出错了。。。。
![image](https://user-images.githubusercontent.com/34341763/198392834-64194fce-17fc-47ad-a3d2-67ca25af1e08.png)
![image](https://user-images.githubusercontent.com/34341763/198392898-53387dfd-b4df-4a46-9de4-001ace1df481.png)
nin您瞧这代码，只有两个0，0是交替打印的，而且第二幅图后边test2的输出反而顺序居然出现了9 → 8

**Comment by SpencerChou** [comment]
好像找到问题了。。。。是深拷贝的问题，我对深拷贝理解还是浅了。。。

**Comment by theanarkh** [comment]
嗯嗯，语言层面自己琢磨下。

**Comment by SpencerChou** [comment]
大佬，在网上看了一下，如何 在for循环中 链式顺序调用 promise  then的方案

```
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

for (let i = 0, p = Promise.resolve(); i < 10; i++) {
    p = p.then(() => delay(Math.random() * 1000))
         .then(() => console.log(i));
}
```

其中使用p的这种方式，能够使得异步的promise能够在for循环中 顺序同步的进行下去。于是 我在上边的 同步threadpool中试图使用这种方案


```
const { defaultThreadPool } = require('nodejs-threadpool').threadPool;

test_cpu_bound = async function({idx,jj}){
    s = 0
    for (let i=0;i<jj;i++){
        s = s + i
    }
    // return idx
    // console.log(idx,s)
    return idx
        
} 
o2 = {
    queue : [],
    processing : false,
    queue_result:[],
    submit: async function (task) {
        this.processing = true;
        const work = await defaultThreadPool.submit(task.context.file || "function({a, b}) { return a + b; }", task.context.params);
        if (~~task.context.timeout) {
            work.setTimeout(~~task.context.timeout);
            work.on('timeout', () => {
                task.reject(new Error('timeout'));
            });
        }
        const done = (err, result) => {
            err ? task.reject(err) : task.resolve(result);
            if (this.queue.length) {
                this.submit(this.queue.shift());
            } else {
                processing = false;
            }
        };
        work.on('error', (error) => {
            done(new Error(error));
        });
        work.on('done', (result) => {
            done(null, result)
        });
    },
    enqueue : function (context) {
        return new Promise((resolve, reject) => {
            const task = {
                context,
                resolve,
                reject
            };
            if (this.processing) {
                this.queue.push(task);
            } else {
                this.submit(task);
            }
        })
    }
}

async function dispatcher_test1(o,cha){
    x = []
    const j=[0,1,2,3,4,5,6,7,8,9]
    let flag = 1
    let cnt = 0
    for(let i=0,p= Promise.resolve();i<10;i++){
        context={file:new String(test_cpu_bound),params:{idx:i,jj:1000000?cha==='test1':800000,timeout:1000}}
        p = p.then( ()=>o.enqueue(context)).then((result)=>console.log(result,cha,'first'));
}
dispatcher_test1(Object.assign({},o2),'test1')
```

但是输出结果却只有如下
![image](https://user-images.githubusercontent.com/34341763/224680441-123be3ea-cbbf-4816-971b-fda7c7961481.png)
好像只有最后一个调用了，但是目前试了很多办法找不到是为何。

我的目的是能够异步的同时跑多个for循环在一个线程的事件循环中，如此异步dispatcher函数，多次调用是能够异步的跑两个for循环的，但是for循环中的 promise异步对象，好像缺无法同步，如果只是线程池，通过之前您的设计，是同步了，但是如果promise中想再嵌套别的异步，比如settimeout，比如发送http请求等，却无法同步进行了，并且o.enqueue的result无法传递到下一个then中，让我十分苦恼

**Comment by SpencerChou** [comment]
那个 StackOverflow帖子如下
https://stackoverflow.com/a/40329190/19830866

**Comment by SpencerChou** [comment]
> 好像只有最后一个调用了，但是目前试了很多办法找不到是为何。

应该是第一个 enqueue之后就无法进行了，是因为 后面的enqueue是 queue.push而不是submit，没有resolve吗

**Comment by SpencerChou** [comment]
> 好像只有最后一个调用了，但是目前试了很多办法找不到是为何。

应该是第一个 enqueue之后就无法进行了，是因为 后面的enqueue是 queue.push而不是submit，没有resolve吗

**Comment by SpencerChou** [comment]
`p = p.then( ()=>{o.enqueue(context)}).then((result)=>{console.log(xx,result,cha,'first')});`

如果代码如上，结果是这样
![image](https://user-images.githubusercontent.com/34341763/224721059-638b42ad-abd5-44ea-8a7b-b6942a7ead1e.png)
结果不能进入下一个then，

`p = p.then( ()=>{return  o.enqueue(context)}).then((result)=>{console.log(xx,result,cha,'first')});`
如果代码如上，结果是这样
![image](https://user-images.githubusercontent.com/34341763/224721294-b522bebb-9bab-40b0-8446-30eafe72dd5a.png)
只有第一个执行了，后面的都卡住了
